name: authentication_repository
description: Repository to manage authentication.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: 3.16.0

dependencies:
  equatable: ^2.0.5
  firebase_auth: ^4.14.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.0
  very_good_analysis: ^5.1.0
