// ignore_for_file: public_member_api_docs

class FakeResponses {
  static String whatIsFlutterResponse = '''
{
   "summary":"Flutter is a free and open source software development kit (SDK) from Google [1]. It's used to create beautiful, fast user experiences for mobile, web, and desktop applications [1]. Flutter works with existing code and is used by developers and organizations around the world [1]. [3]. Flutter is a fully open source project [3].",
   "total_size":694,
   "attribution_token":"Z_BmCgwIm4iYqwYQ1r7FvwMSJDY1NjAyMmJhLTAwMDAtMjgwZi04NGIwLWQ0ZjU0N2ZhYjdhMCIHR0VORVJJQyoowZWMIqKGjiKmi-8XxcvzF9SynRWcho4iwvCeFaOAlyKOvp0VvpWMIg",
   "next_page_token":"ATY3IWYmdDN1YGNk1CMiRDOtYGM4ITLwADMw0SOiJjMwYTN2QiGDEMs5jJEGs6pxvJCMIBMxIgC",
   "documents":[
      {
         "id":"49e63c23-8376-440a-ac6e-98675fdd023e",
         "metadata":{
            "url":"https://api.flutter.dev/index.html",
            "title":"Flutter - Dart API docs",
            "tags":"missing",
            "keywords":null,
            "description":"Flutter is <b>Google&#39;s SDK for crafting beautiful, fast user experiences for mobile, web, and desktop from a single codebase</b>. Flutter works with existing code, is used by developers and organizations around the world, and is free and open source.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/index.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-index-html.html",
         "snippets":[
            "inspector. dart:math Mathematical constants and functions, plus a random number generator. dart:typed_data Lists that efficiently handle fixed sized data (for&nbsp;..."
         ]
      },
      {
         "id":"af6dcbfb-f11b-443f-8af0-5bdcfcdd8102",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/FlutterEngine.html",
            "title":"FlutterEngine",
            "tags":"missing",
            "keywords":null,
            "description":"The FlutterEngine is the container through which Dart code can be run in an Android application. Dart code in a FlutterEngine can execute in the background, or it can be render to the screen by using the accompanying FlutterRenderer and Dart code using the Flutter framework on the Dart side.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/FlutterEngine.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-embedding-engine-flutterengine-html.html",
         "snippets":[
            "to be notified of <b>Flutter</b> ... LocalizationPlugin getLocalizationPlugin() The LocalizationPlugin this <b>FlutterEngine</b> created. MouseCursorChannel&nbsp;..."
         ]
      },
      {
         "id":"2746919b-8bf2-4c5b-8289-742b533da9fa",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/",
            "title":"Flutter Reference",
            "tags":"mock",
            "keywords":null,
            "description":"Flutter is a fully open source project, and we welcome contributions. Information on how to get started can be found at our contributor guide. \u00a9 2023 Flutter. All rights reserved. (Last updated: 2023-10-25) Generated by jazzy \u266a\u266b v0.14.3, a Realm project.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc.html",
         "snippets":[
            "... <b>FlutterStandardMessageCodec FlutterStandardMethodCodec FlutterStandardReader FlutterStandardReaderWriter FlutterStandardTypedData FlutterStandardWriter</b>&nbsp;..."
         ]
      },
      {
         "id":"88318aee-2f63-456b-8ea0-1a5dd90b0ef3",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/app/package-summary.html",
            "title":"io.flutter.app",
            "tags":"fake",
            "keywords":null,
            "description":"FlutterActivityEvents A collection of Android Activity methods that are relevant to the core operation of Flutter applications. Class Summary Class Description FlutterActivity Deprecated. FlutterActivity is the new API that now replaces this class.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/app/package-summary.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-app-package-summary-html.html",
         "snippets":[
            
         ]
      },
      {
         "id":"140f1ff5-9c62-4e4e-ba47-fcdb7c96de33",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/Classes/FlutterEngine.html",
            "title":"FlutterEngine Class Reference",
            "tags":"missing",
            "keywords":null,
            "description":"A FlutterEngine can also be used to prewarm the Dart execution environment and reduce the latency of showing the Flutter screen when a FlutterViewController is created and presented. See http://flutter.dev/docs/development/add-to-app/performance for more details on loading performance.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/Classes/FlutterEngine.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc-classes-flutterengine-html.html",
         "snippets":[
            "libraryURI: String?, initialRoute: String?) -&gt; Bool Parameters entrypoint The name of a top-level function from a Dart library. If this is&nbsp;..."
         ]
      },
      {
         "id":"57980044-93db-430a-a0dd-caacb6e0830c",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterActivity.html",
            "title":"FlutterActivity",
            "tags":"fake",
            "keywords":null,
            "description":"Using a FlutterFragment requires forwarding some calls from an Activity to the FlutterFragment. If Flutter is needed in a location that can only use a View, consider using a FlutterView.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterActivity.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-embedding-android-flutteractivity-html.html",
         "snippets":[
            "FlutterFragment. If <b>Flutter</b> ... ACCOUNT_SERVICE, ACTIVITY_SERVICE, ALARM_SERVICE, APP_OPS_SERVICE, APP_SEARCH_SERVICE, APPWIDGET_SERVICE, AUDIO_SERVICE,&nbsp;..."
         ]
      },
      {
         "id":"f961196f-7a50-4296-9867-20d94d5c92f4",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/Classes/FlutterViewController.html",
            "title":"FlutterViewController Class Reference",
            "tags":"unknown",
            "keywords":null,
            "description":"Flutter&#39;s rendering is asynchronous, so the first frame rendered by the Flutter application might not immediately appear when the Flutter view is initially placed in the view hierarchy. The splash screen view will be used as a replacement until the first frame is rendered.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/Classes/FlutterViewController.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc-classes-flutterviewcontroller-html.html",
         "snippets":[
            "... Swift init(coder aDecoder: NSCoder) -<b>setFlutterViewDidRenderCallback</b>: Registers a callback that will be invoked when the <b>Flutter</b> view has been rendered."
         ]
      },
      {
         "id":"70177a4a-78fd-4540-91d1-165f918cd4f4",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/FlutterPlugin.html",
            "title":"FlutterPlugin",
            "tags":"unknown",
            "keywords":null,
            "description":"A Flutter plugin allows Flutter developers to interact with a host platform, eg, Android and iOS, via Dart code. It includes platform code, as well as Dart code.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/FlutterPlugin.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-embedding-engine-plugins-flutterplugin-html.html",
         "snippets":[
            "your browser. Summary: Nested | Field | Constr | Method Detail: Field | Constr | Method. https api <b>flutter</b> dev javadoc io <b>flutter</b> embedding engine plugins&nbsp;..."
         ]
      },
      {
         "id":"c3cd5194-8da3-4809-a88a-cc4ad1026871",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/Classes/FlutterAppDelegate.html",
            "title":"FlutterAppDelegate Class Reference",
            "tags":"fake",
            "keywords":null,
            "description":"This class implements the following behaviors: Status bar touches are forwarded to the key window&#39;s root view FlutterViewController, in order to trigger scroll to top.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/Classes/FlutterAppDelegate.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc-classes-flutterappdelegate-html.html",
         "snippets":[
            
         ]
      },
      {
         "id":"3821e382-276d-43b7-8368-0f9f9b9268d0",
         "metadata":{
            "url":"https://api.flutter.dev/flutter/widgets/Navigator-class.html",
            "title":"Navigator class - widgets library - Dart API",
            "tags":"unknown",
            "keywords":null,
            "description":"Navigator class - widgets library - Dart API menu Flutter widgets Navigator class Navigator brightness_4 brightness_5 description Navigator class A widget that manages a set of child widgets with a stack discipline.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/flutter/widgets/Navigator-class.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-flutter-widgets-navigator-class-html.html",
         "snippets":[
            "pushed route&#39;s Future as described above. Callers can await the returned value to take an action when the route is popped, or to discover the route&#39;s value."
         ]
      }
   ]
}
''';
  static String platformsResponse = '''
{
   "summary":"Flutter is a free and open source software development kit (SDK) from Google [1]. It's used to create beautiful, fast user experiences for mobile, web, and desktop applications [1]. Flutter works with existing code and is used by developers and organizations around the world [1]. [3]. Flutter is a fully open source project [3].",
   "total_size":694,
   "attribution_token":"Z_BmCgwIm4iYqwYQ1r7FvwMSJDY1NjAyMmJhLTAwMDAtMjgwZi04NGIwLWQ0ZjU0N2ZhYjdhMCIHR0VORVJJQyoowZWMIqKGjiKmi-8XxcvzF9SynRWcho4iwvCeFaOAlyKOvp0VvpWMIg",
   "next_page_token":"ATY3IWYmdDN1YGNk1CMiRDOtYGM4ITLwADMw0SOiJjMwYTN2QiGDEMs5jJEGs6pxvJCMIBMxIgC",
   "documents":[
      {
         "id":"49e63c23-8376-440a-ac6e-98675fdd023e",
         "metadata":{
            "url":"https://api.flutter.dev/index.html",
            "title":"Flutter - Dart API docs",
            "tags":"missing",
            "keywords":null,
            "description":"Flutter is <b>Google&#39;s SDK for crafting beautiful, fast user experiences for mobile, web, and desktop from a single codebase</b>. Flutter works with existing code, is used by developers and organizations around the world, and is free and open source.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/index.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-index-html.html",
         "snippets":[
            "inspector. dart:math Mathematical constants and functions, plus a random number generator. dart:typed_data Lists that efficiently handle fixed sized data (for&nbsp;..."
         ]
      },
      {
         "id":"af6dcbfb-f11b-443f-8af0-5bdcfcdd8102",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/FlutterEngine.html",
            "title":"FlutterEngine",
            "tags":"missing",
            "keywords":null,
            "description":"The FlutterEngine is the container through which Dart code can be run in an Android application. Dart code in a FlutterEngine can execute in the background, or it can be render to the screen by using the accompanying FlutterRenderer and Dart code using the Flutter framework on the Dart side.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/FlutterEngine.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-embedding-engine-flutterengine-html.html",
         "snippets":[
            "to be notified of <b>Flutter</b> ... LocalizationPlugin getLocalizationPlugin() The LocalizationPlugin this <b>FlutterEngine</b> created. MouseCursorChannel&nbsp;..."
         ]
      },
      {
         "id":"2746919b-8bf2-4c5b-8289-742b533da9fa",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/",
            "title":"Flutter Reference",
            "tags":"mock",
            "keywords":null,
            "description":"Flutter is a fully open source project, and we welcome contributions. Information on how to get started can be found at our contributor guide. \u00a9 2023 Flutter. All rights reserved. (Last updated: 2023-10-25) Generated by jazzy \u266a\u266b v0.14.3, a Realm project.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc.html",
         "snippets":[
            "... <b>FlutterStandardMessageCodec FlutterStandardMethodCodec FlutterStandardReader FlutterStandardReaderWriter FlutterStandardTypedData FlutterStandardWriter</b>&nbsp;..."
         ]
      },
      {
         "id":"88318aee-2f63-456b-8ea0-1a5dd90b0ef3",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/app/package-summary.html",
            "title":"io.flutter.app",
            "tags":"fake",
            "keywords":null,
            "description":"FlutterActivityEvents A collection of Android Activity methods that are relevant to the core operation of Flutter applications. Class Summary Class Description FlutterActivity Deprecated. FlutterActivity is the new API that now replaces this class.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/app/package-summary.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-app-package-summary-html.html",
         "snippets":[
            
         ]
      },
      {
         "id":"140f1ff5-9c62-4e4e-ba47-fcdb7c96de33",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/Classes/FlutterEngine.html",
            "title":"FlutterEngine Class Reference",
            "tags":"missing",
            "keywords":null,
            "description":"A FlutterEngine can also be used to prewarm the Dart execution environment and reduce the latency of showing the Flutter screen when a FlutterViewController is created and presented. See http://flutter.dev/docs/development/add-to-app/performance for more details on loading performance.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/Classes/FlutterEngine.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc-classes-flutterengine-html.html",
         "snippets":[
            "libraryURI: String?, initialRoute: String?) -&gt; Bool Parameters entrypoint The name of a top-level function from a Dart library. If this is&nbsp;..."
         ]
      },
      {
         "id":"57980044-93db-430a-a0dd-caacb6e0830c",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterActivity.html",
            "title":"FlutterActivity",
            "tags":"fake",
            "keywords":null,
            "description":"Using a FlutterFragment requires forwarding some calls from an Activity to the FlutterFragment. If Flutter is needed in a location that can only use a View, consider using a FlutterView.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterActivity.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-embedding-android-flutteractivity-html.html",
         "snippets":[
            "FlutterFragment. If <b>Flutter</b> ... ACCOUNT_SERVICE, ACTIVITY_SERVICE, ALARM_SERVICE, APP_OPS_SERVICE, APP_SEARCH_SERVICE, APPWIDGET_SERVICE, AUDIO_SERVICE,&nbsp;..."
         ]
      },
      {
         "id":"f961196f-7a50-4296-9867-20d94d5c92f4",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/Classes/FlutterViewController.html",
            "title":"FlutterViewController Class Reference",
            "tags":"unknown",
            "keywords":null,
            "description":"Flutter&#39;s rendering is asynchronous, so the first frame rendered by the Flutter application might not immediately appear when the Flutter view is initially placed in the view hierarchy. The splash screen view will be used as a replacement until the first frame is rendered.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/Classes/FlutterViewController.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc-classes-flutterviewcontroller-html.html",
         "snippets":[
            "... Swift init(coder aDecoder: NSCoder) -<b>setFlutterViewDidRenderCallback</b>: Registers a callback that will be invoked when the <b>Flutter</b> view has been rendered."
         ]
      },
      {
         "id":"70177a4a-78fd-4540-91d1-165f918cd4f4",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/FlutterPlugin.html",
            "title":"FlutterPlugin",
            "tags":"unknown",
            "keywords":null,
            "description":"A Flutter plugin allows Flutter developers to interact with a host platform, eg, Android and iOS, via Dart code. It includes platform code, as well as Dart code.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/FlutterPlugin.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-embedding-engine-plugins-flutterplugin-html.html",
         "snippets":[
            "your browser. Summary: Nested | Field | Constr | Method Detail: Field | Constr | Method. https api <b>flutter</b> dev javadoc io <b>flutter</b> embedding engine plugins&nbsp;..."
         ]
      },
      {
         "id":"c3cd5194-8da3-4809-a88a-cc4ad1026871",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/Classes/FlutterAppDelegate.html",
            "title":"FlutterAppDelegate Class Reference",
            "tags":"fake",
            "keywords":null,
            "description":"This class implements the following behaviors: Status bar touches are forwarded to the key window&#39;s root view FlutterViewController, in order to trigger scroll to top.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/Classes/FlutterAppDelegate.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc-classes-flutterappdelegate-html.html",
         "snippets":[
            
         ]
      },
      {
         "id":"3821e382-276d-43b7-8368-0f9f9b9268d0",
         "metadata":{
            "url":"https://api.flutter.dev/flutter/widgets/Navigator-class.html",
            "title":"Navigator class - widgets library - Dart API",
            "tags":"unknown",
            "keywords":null,
            "description":"Navigator class - widgets library - Dart API menu Flutter widgets Navigator class Navigator brightness_4 brightness_5 description Navigator class A widget that manages a set of child widgets with a stack discipline.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/flutter/widgets/Navigator-class.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-flutter-widgets-navigator-class-html.html",
         "snippets":[
            "pushed route&#39;s Future as described above. Callers can await the returned value to take an action when the route is popped, or to discover the route&#39;s value."
         ]
      }
   ]
}
''';
  static String languageResponse = '''
{
   "summary":"Flutter is a free and open source software development kit (SDK) from Google [1]. It's used to create beautiful, fast user experiences for mobile, web, and desktop applications [1]. Flutter works with existing code and is used by developers and organizations around the world [1]. [3]. Flutter is a fully open source project [3].",
   "total_size":694,
   "attribution_token":"Z_BmCgwIm4iYqwYQ1r7FvwMSJDY1NjAyMmJhLTAwMDAtMjgwZi04NGIwLWQ0ZjU0N2ZhYjdhMCIHR0VORVJJQyoowZWMIqKGjiKmi-8XxcvzF9SynRWcho4iwvCeFaOAlyKOvp0VvpWMIg",
   "next_page_token":"ATY3IWYmdDN1YGNk1CMiRDOtYGM4ITLwADMw0SOiJjMwYTN2QiGDEMs5jJEGs6pxvJCMIBMxIgC",
   "documents":[
      {
         "id":"49e63c23-8376-440a-ac6e-98675fdd023e",
         "metadata":{
            "url":"https://api.flutter.dev/index.html",
            "title":"Flutter - Dart API docs",
            "tags":"missing",
            "keywords":null,
            "description":"Flutter is <b>Google&#39;s SDK for crafting beautiful, fast user experiences for mobile, web, and desktop from a single codebase</b>. Flutter works with existing code, is used by developers and organizations around the world, and is free and open source.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/index.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-index-html.html",
         "snippets":[
            "inspector. dart:math Mathematical constants and functions, plus a random number generator. dart:typed_data Lists that efficiently handle fixed sized data (for&nbsp;..."
         ]
      },
      {
         "id":"af6dcbfb-f11b-443f-8af0-5bdcfcdd8102",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/FlutterEngine.html",
            "title":"FlutterEngine",
            "tags":"missing",
            "keywords":null,
            "description":"The FlutterEngine is the container through which Dart code can be run in an Android application. Dart code in a FlutterEngine can execute in the background, or it can be render to the screen by using the accompanying FlutterRenderer and Dart code using the Flutter framework on the Dart side.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/FlutterEngine.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-embedding-engine-flutterengine-html.html",
         "snippets":[
            "to be notified of <b>Flutter</b> ... LocalizationPlugin getLocalizationPlugin() The LocalizationPlugin this <b>FlutterEngine</b> created. MouseCursorChannel&nbsp;..."
         ]
      },
      {
         "id":"2746919b-8bf2-4c5b-8289-742b533da9fa",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/",
            "title":"Flutter Reference",
            "tags":"mock",
            "keywords":null,
            "description":"Flutter is a fully open source project, and we welcome contributions. Information on how to get started can be found at our contributor guide. \u00a9 2023 Flutter. All rights reserved. (Last updated: 2023-10-25) Generated by jazzy \u266a\u266b v0.14.3, a Realm project.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc.html",
         "snippets":[
            "... <b>FlutterStandardMessageCodec FlutterStandardMethodCodec FlutterStandardReader FlutterStandardReaderWriter FlutterStandardTypedData FlutterStandardWriter</b>&nbsp;..."
         ]
      },
      {
         "id":"88318aee-2f63-456b-8ea0-1a5dd90b0ef3",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/app/package-summary.html",
            "title":"io.flutter.app",
            "tags":"fake",
            "keywords":null,
            "description":"FlutterActivityEvents A collection of Android Activity methods that are relevant to the core operation of Flutter applications. Class Summary Class Description FlutterActivity Deprecated. FlutterActivity is the new API that now replaces this class.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/app/package-summary.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-app-package-summary-html.html",
         "snippets":[
            
         ]
      },
      {
         "id":"140f1ff5-9c62-4e4e-ba47-fcdb7c96de33",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/Classes/FlutterEngine.html",
            "title":"FlutterEngine Class Reference",
            "tags":"missing",
            "keywords":null,
            "description":"A FlutterEngine can also be used to prewarm the Dart execution environment and reduce the latency of showing the Flutter screen when a FlutterViewController is created and presented. See http://flutter.dev/docs/development/add-to-app/performance for more details on loading performance.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/Classes/FlutterEngine.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc-classes-flutterengine-html.html",
         "snippets":[
            "libraryURI: String?, initialRoute: String?) -&gt; Bool Parameters entrypoint The name of a top-level function from a Dart library. If this is&nbsp;..."
         ]
      },
      {
         "id":"57980044-93db-430a-a0dd-caacb6e0830c",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterActivity.html",
            "title":"FlutterActivity",
            "tags":"fake",
            "keywords":null,
            "description":"Using a FlutterFragment requires forwarding some calls from an Activity to the FlutterFragment. If Flutter is needed in a location that can only use a View, consider using a FlutterView.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterActivity.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-embedding-android-flutteractivity-html.html",
         "snippets":[
            "FlutterFragment. If <b>Flutter</b> ... ACCOUNT_SERVICE, ACTIVITY_SERVICE, ALARM_SERVICE, APP_OPS_SERVICE, APP_SEARCH_SERVICE, APPWIDGET_SERVICE, AUDIO_SERVICE,&nbsp;..."
         ]
      },
      {
         "id":"f961196f-7a50-4296-9867-20d94d5c92f4",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/Classes/FlutterViewController.html",
            "title":"FlutterViewController Class Reference",
            "tags":"unknown",
            "keywords":null,
            "description":"Flutter&#39;s rendering is asynchronous, so the first frame rendered by the Flutter application might not immediately appear when the Flutter view is initially placed in the view hierarchy. The splash screen view will be used as a replacement until the first frame is rendered.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/Classes/FlutterViewController.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc-classes-flutterviewcontroller-html.html",
         "snippets":[
            "... Swift init(coder aDecoder: NSCoder) -<b>setFlutterViewDidRenderCallback</b>: Registers a callback that will be invoked when the <b>Flutter</b> view has been rendered."
         ]
      },
      {
         "id":"70177a4a-78fd-4540-91d1-165f918cd4f4",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/FlutterPlugin.html",
            "title":"FlutterPlugin",
            "tags":"unknown",
            "keywords":null,
            "description":"A Flutter plugin allows Flutter developers to interact with a host platform, eg, Android and iOS, via Dart code. It includes platform code, as well as Dart code.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/FlutterPlugin.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-embedding-engine-plugins-flutterplugin-html.html",
         "snippets":[
            "your browser. Summary: Nested | Field | Constr | Method Detail: Field | Constr | Method. https api <b>flutter</b> dev javadoc io <b>flutter</b> embedding engine plugins&nbsp;..."
         ]
      },
      {
         "id":"c3cd5194-8da3-4809-a88a-cc4ad1026871",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/Classes/FlutterAppDelegate.html",
            "title":"FlutterAppDelegate Class Reference",
            "tags":"fake",
            "keywords":null,
            "description":"This class implements the following behaviors: Status bar touches are forwarded to the key window&#39;s root view FlutterViewController, in order to trigger scroll to top.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/Classes/FlutterAppDelegate.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc-classes-flutterappdelegate-html.html",
         "snippets":[
            
         ]
      },
      {
         "id":"3821e382-276d-43b7-8368-0f9f9b9268d0",
         "metadata":{
            "url":"https://api.flutter.dev/flutter/widgets/Navigator-class.html",
            "title":"Navigator class - widgets library - Dart API",
            "tags":"unknown",
            "keywords":null,
            "description":"Navigator class - widgets library - Dart API menu Flutter widgets Navigator class Navigator brightness_4 brightness_5 description Navigator class A widget that manages a set of child widgets with a stack discipline.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/flutter/widgets/Navigator-class.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-flutter-widgets-navigator-class-html.html",
         "snippets":[
            "pushed route&#39;s Future as described above. Callers can await the returned value to take an action when the route is popped, or to discover the route&#39;s value."
         ]
      }
   ]
}
''';
  static String hotReloadResponse = '''
{
   "summary":"Flutter is a free and open source software development kit (SDK) from Google [1]. It's used to create beautiful, fast user experiences for mobile, web, and desktop applications [1]. Flutter works with existing code and is used by developers and organizations around the world [1]. [3]. Flutter is a fully open source project [3].",
   "total_size":694,
   "attribution_token":"Z_BmCgwIm4iYqwYQ1r7FvwMSJDY1NjAyMmJhLTAwMDAtMjgwZi04NGIwLWQ0ZjU0N2ZhYjdhMCIHR0VORVJJQyoowZWMIqKGjiKmi-8XxcvzF9SynRWcho4iwvCeFaOAlyKOvp0VvpWMIg",
   "next_page_token":"ATY3IWYmdDN1YGNk1CMiRDOtYGM4ITLwADMw0SOiJjMwYTN2QiGDEMs5jJEGs6pxvJCMIBMxIgC",
   "documents":[
      {
         "id":"49e63c23-8376-440a-ac6e-98675fdd023e",
         "metadata":{
            "url":"https://api.flutter.dev/index.html",
            "title":"Flutter - Dart API docs",
            "tags":"missing",
            "keywords":null,
            "description":"Flutter is <b>Google&#39;s SDK for crafting beautiful, fast user experiences for mobile, web, and desktop from a single codebase</b>. Flutter works with existing code, is used by developers and organizations around the world, and is free and open source.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/index.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-index-html.html",
         "snippets":[
            "inspector. dart:math Mathematical constants and functions, plus a random number generator. dart:typed_data Lists that efficiently handle fixed sized data (for&nbsp;..."
         ]
      },
      {
         "id":"af6dcbfb-f11b-443f-8af0-5bdcfcdd8102",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/FlutterEngine.html",
            "title":"FlutterEngine",
            "tags":"missing",
            "keywords":null,
            "description":"The FlutterEngine is the container through which Dart code can be run in an Android application. Dart code in a FlutterEngine can execute in the background, or it can be render to the screen by using the accompanying FlutterRenderer and Dart code using the Flutter framework on the Dart side.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/FlutterEngine.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-embedding-engine-flutterengine-html.html",
         "snippets":[
            "to be notified of <b>Flutter</b> ... LocalizationPlugin getLocalizationPlugin() The LocalizationPlugin this <b>FlutterEngine</b> created. MouseCursorChannel&nbsp;..."
         ]
      },
      {
         "id":"2746919b-8bf2-4c5b-8289-742b533da9fa",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/",
            "title":"Flutter Reference",
            "tags":"mock",
            "keywords":null,
            "description":"Flutter is a fully open source project, and we welcome contributions. Information on how to get started can be found at our contributor guide. \u00a9 2023 Flutter. All rights reserved. (Last updated: 2023-10-25) Generated by jazzy \u266a\u266b v0.14.3, a Realm project.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc.html",
         "snippets":[
            "... <b>FlutterStandardMessageCodec FlutterStandardMethodCodec FlutterStandardReader FlutterStandardReaderWriter FlutterStandardTypedData FlutterStandardWriter</b>&nbsp;..."
         ]
      },
      {
         "id":"88318aee-2f63-456b-8ea0-1a5dd90b0ef3",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/app/package-summary.html",
            "title":"io.flutter.app",
            "tags":"fake",
            "keywords":null,
            "description":"FlutterActivityEvents A collection of Android Activity methods that are relevant to the core operation of Flutter applications. Class Summary Class Description FlutterActivity Deprecated. FlutterActivity is the new API that now replaces this class.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/app/package-summary.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-app-package-summary-html.html",
         "snippets":[
            
         ]
      },
      {
         "id":"140f1ff5-9c62-4e4e-ba47-fcdb7c96de33",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/Classes/FlutterEngine.html",
            "title":"FlutterEngine Class Reference",
            "tags":"missing",
            "keywords":null,
            "description":"A FlutterEngine can also be used to prewarm the Dart execution environment and reduce the latency of showing the Flutter screen when a FlutterViewController is created and presented. See http://flutter.dev/docs/development/add-to-app/performance for more details on loading performance.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/Classes/FlutterEngine.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc-classes-flutterengine-html.html",
         "snippets":[
            "libraryURI: String?, initialRoute: String?) -&gt; Bool Parameters entrypoint The name of a top-level function from a Dart library. If this is&nbsp;..."
         ]
      },
      {
         "id":"57980044-93db-430a-a0dd-caacb6e0830c",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterActivity.html",
            "title":"FlutterActivity",
            "tags":"fake",
            "keywords":null,
            "description":"Using a FlutterFragment requires forwarding some calls from an Activity to the FlutterFragment. If Flutter is needed in a location that can only use a View, consider using a FlutterView.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterActivity.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-embedding-android-flutteractivity-html.html",
         "snippets":[
            "FlutterFragment. If <b>Flutter</b> ... ACCOUNT_SERVICE, ACTIVITY_SERVICE, ALARM_SERVICE, APP_OPS_SERVICE, APP_SEARCH_SERVICE, APPWIDGET_SERVICE, AUDIO_SERVICE,&nbsp;..."
         ]
      },
      {
         "id":"f961196f-7a50-4296-9867-20d94d5c92f4",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/Classes/FlutterViewController.html",
            "title":"FlutterViewController Class Reference",
            "tags":"unknown",
            "keywords":null,
            "description":"Flutter&#39;s rendering is asynchronous, so the first frame rendered by the Flutter application might not immediately appear when the Flutter view is initially placed in the view hierarchy. The splash screen view will be used as a replacement until the first frame is rendered.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/Classes/FlutterViewController.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc-classes-flutterviewcontroller-html.html",
         "snippets":[
            "... Swift init(coder aDecoder: NSCoder) -<b>setFlutterViewDidRenderCallback</b>: Registers a callback that will be invoked when the <b>Flutter</b> view has been rendered."
         ]
      },
      {
         "id":"70177a4a-78fd-4540-91d1-165f918cd4f4",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/FlutterPlugin.html",
            "title":"FlutterPlugin",
            "tags":"unknown",
            "keywords":null,
            "description":"A Flutter plugin allows Flutter developers to interact with a host platform, eg, Android and iOS, via Dart code. It includes platform code, as well as Dart code.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/FlutterPlugin.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-embedding-engine-plugins-flutterplugin-html.html",
         "snippets":[
            "your browser. Summary: Nested | Field | Constr | Method Detail: Field | Constr | Method. https api <b>flutter</b> dev javadoc io <b>flutter</b> embedding engine plugins&nbsp;..."
         ]
      },
      {
         "id":"c3cd5194-8da3-4809-a88a-cc4ad1026871",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/Classes/FlutterAppDelegate.html",
            "title":"FlutterAppDelegate Class Reference",
            "tags":"fake",
            "keywords":null,
            "description":"This class implements the following behaviors: Status bar touches are forwarded to the key window&#39;s root view FlutterViewController, in order to trigger scroll to top.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/Classes/FlutterAppDelegate.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc-classes-flutterappdelegate-html.html",
         "snippets":[
            
         ]
      },
      {
         "id":"3821e382-276d-43b7-8368-0f9f9b9268d0",
         "metadata":{
            "url":"https://api.flutter.dev/flutter/widgets/Navigator-class.html",
            "title":"Navigator class - widgets library - Dart API",
            "tags":"unknown",
            "keywords":null,
            "description":"Navigator class - widgets library - Dart API menu Flutter widgets Navigator class Navigator brightness_4 brightness_5 description Navigator class A widget that manages a set of child widgets with a stack discipline.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/flutter/widgets/Navigator-class.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-flutter-widgets-navigator-class-html.html",
         "snippets":[
            "pushed route&#39;s Future as described above. Callers can await the returned value to take an action when the route is popped, or to discover the route&#39;s value."
         ]
      }
   ]
}
''';
  static String invalidResponse = '''
{
   "summary":"Flutter is a free and open source software development kit (SDK) from Google [1]. It's used to create beautiful, fast user experiences for mobile, web, and desktop applications [1]. Flutter works with existing code and is used by developers and organizations around the world [1]. [3]. Flutter is a fully open source project [3].",
   "total_size":694,
   "attribution_token":"Z_BmCgwIm4iYqwYQ1r7FvwMSJDY1NjAyMmJhLTAwMDAtMjgwZi04NGIwLWQ0ZjU0N2ZhYjdhMCIHR0VORVJJQyoowZWMIqKGjiKmi-8XxcvzF9SynRWcho4iwvCeFaOAlyKOvp0VvpWMIg",
   "next_page_token":"ATY3IWYmdDN1YGNk1CMiRDOtYGM4ITLwADMw0SOiJjMwYTN2QiGDEMs5jJEGs6pxvJCMIBMxIgC",
   "documents":[
      {
         "id":"49e63c23-8376-440a-ac6e-98675fdd023e",
         "metadata":{
            "url":"https://api.flutter.dev/index.html",
            "title":"Flutter - Dart API docs",
            "tags":"missing",
            "keywords":null,
            "description":"Flutter is <b>Google&#39;s SDK for crafting beautiful, fast user experiences for mobile, web, and desktop from a single codebase</b>. Flutter works with existing code, is used by developers and organizations around the world, and is free and open source.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/index.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-index-html.html",
         "snippets":[
            "inspector. dart:math Mathematical constants and functions, plus a random number generator. dart:typed_data Lists that efficiently handle fixed sized data (for&nbsp;..."
         ]
      },
      {
         "id":"af6dcbfb-f11b-443f-8af0-5bdcfcdd8102",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/FlutterEngine.html",
            "title":"FlutterEngine",
            "tags":"missing",
            "keywords":null,
            "description":"The FlutterEngine is the container through which Dart code can be run in an Android application. Dart code in a FlutterEngine can execute in the background, or it can be render to the screen by using the accompanying FlutterRenderer and Dart code using the Flutter framework on the Dart side.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/FlutterEngine.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-embedding-engine-flutterengine-html.html",
         "snippets":[
            "to be notified of <b>Flutter</b> ... LocalizationPlugin getLocalizationPlugin() The LocalizationPlugin this <b>FlutterEngine</b> created. MouseCursorChannel&nbsp;..."
         ]
      },
      {
         "id":"2746919b-8bf2-4c5b-8289-742b533da9fa",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/",
            "title":"Flutter Reference",
            "tags":"mock",
            "keywords":null,
            "description":"Flutter is a fully open source project, and we welcome contributions. Information on how to get started can be found at our contributor guide. \u00a9 2023 Flutter. All rights reserved. (Last updated: 2023-10-25) Generated by jazzy \u266a\u266b v0.14.3, a Realm project.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc.html",
         "snippets":[
            "... <b>FlutterStandardMessageCodec FlutterStandardMethodCodec FlutterStandardReader FlutterStandardReaderWriter FlutterStandardTypedData FlutterStandardWriter</b>&nbsp;..."
         ]
      },
      {
         "id":"88318aee-2f63-456b-8ea0-1a5dd90b0ef3",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/app/package-summary.html",
            "title":"io.flutter.app",
            "tags":"fake",
            "keywords":null,
            "description":"FlutterActivityEvents A collection of Android Activity methods that are relevant to the core operation of Flutter applications. Class Summary Class Description FlutterActivity Deprecated. FlutterActivity is the new API that now replaces this class.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/app/package-summary.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-app-package-summary-html.html",
         "snippets":[
            
         ]
      },
      {
         "id":"140f1ff5-9c62-4e4e-ba47-fcdb7c96de33",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/Classes/FlutterEngine.html",
            "title":"FlutterEngine Class Reference",
            "tags":"missing",
            "keywords":null,
            "description":"A FlutterEngine can also be used to prewarm the Dart execution environment and reduce the latency of showing the Flutter screen when a FlutterViewController is created and presented. See http://flutter.dev/docs/development/add-to-app/performance for more details on loading performance.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/Classes/FlutterEngine.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc-classes-flutterengine-html.html",
         "snippets":[
            "libraryURI: String?, initialRoute: String?) -&gt; Bool Parameters entrypoint The name of a top-level function from a Dart library. If this is&nbsp;..."
         ]
      },
      {
         "id":"57980044-93db-430a-a0dd-caacb6e0830c",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterActivity.html",
            "title":"FlutterActivity",
            "tags":"fake",
            "keywords":null,
            "description":"Using a FlutterFragment requires forwarding some calls from an Activity to the FlutterFragment. If Flutter is needed in a location that can only use a View, consider using a FlutterView.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/embedding/android/FlutterActivity.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-embedding-android-flutteractivity-html.html",
         "snippets":[
            "FlutterFragment. If <b>Flutter</b> ... ACCOUNT_SERVICE, ACTIVITY_SERVICE, ALARM_SERVICE, APP_OPS_SERVICE, APP_SEARCH_SERVICE, APPWIDGET_SERVICE, AUDIO_SERVICE,&nbsp;..."
         ]
      },
      {
         "id":"f961196f-7a50-4296-9867-20d94d5c92f4",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/Classes/FlutterViewController.html",
            "title":"FlutterViewController Class Reference",
            "tags":"unknown",
            "keywords":null,
            "description":"Flutter&#39;s rendering is asynchronous, so the first frame rendered by the Flutter application might not immediately appear when the Flutter view is initially placed in the view hierarchy. The splash screen view will be used as a replacement until the first frame is rendered.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/Classes/FlutterViewController.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc-classes-flutterviewcontroller-html.html",
         "snippets":[
            "... Swift init(coder aDecoder: NSCoder) -<b>setFlutterViewDidRenderCallback</b>: Registers a callback that will be invoked when the <b>Flutter</b> view has been rendered."
         ]
      },
      {
         "id":"70177a4a-78fd-4540-91d1-165f918cd4f4",
         "metadata":{
            "url":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/FlutterPlugin.html",
            "title":"FlutterPlugin",
            "tags":"unknown",
            "keywords":null,
            "description":"A Flutter plugin allows Flutter developers to interact with a host platform, eg, Android and iOS, via Dart code. It includes platform code, as well as Dart code.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/javadoc/io/flutter/embedding/engine/plugins/FlutterPlugin.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-javadoc-io-flutter-embedding-engine-plugins-flutterplugin-html.html",
         "snippets":[
            "your browser. Summary: Nested | Field | Constr | Method Detail: Field | Constr | Method. https api <b>flutter</b> dev javadoc io <b>flutter</b> embedding engine plugins&nbsp;..."
         ]
      },
      {
         "id":"c3cd5194-8da3-4809-a88a-cc4ad1026871",
         "metadata":{
            "url":"https://api.flutter.dev/objcdoc/Classes/FlutterAppDelegate.html",
            "title":"FlutterAppDelegate Class Reference",
            "tags":"fake",
            "keywords":null,
            "description":"This class implements the following behaviors: Status bar touches are forwarded to the key window&#39;s root view FlutterViewController, in order to trigger scroll to top.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/objcdoc/Classes/FlutterAppDelegate.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-objcdoc-classes-flutterappdelegate-html.html",
         "snippets":[
            
         ]
      },
      {
         "id":"3821e382-276d-43b7-8368-0f9f9b9268d0",
         "metadata":{
            "url":"https://api.flutter.dev/flutter/widgets/Navigator-class.html",
            "title":"Navigator class - widgets library - Dart API",
            "tags":"unknown",
            "keywords":null,
            "description":"Navigator class - widgets library - Dart API menu Flutter widgets Navigator class Navigator brightness_4 brightness_5 description Navigator class A widget that manages a set of child widgets with a stack discipline.",
            "image_uri":null
         },
         "link":"https://api.flutter.dev/flutter/widgets/Navigator-class.html",
         "doc_link":"gs://flutter-vertex-ai-demo-docs-v1/api-flutter-dev-flutter-widgets-navigator-class-html.html",
         "snippets":[
            "pushed route&#39;s Future as described above. Callers can await the returned value to take an action when the route is popped, or to discover the route&#39;s value."
         ]
      }
   ]
}
''';
}
