name: deploy_app_dev

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    name: Deploy App Development
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.16.0"
      - run: flutter packages get
      - run: flutter build web -t lib/main_development.dart
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DASH_AI_SEARCH_DEVELOPMENT }}'
          channelId: live
          projectId: dash-ai-search-development
          target: app_dev        
